name: warnings
description: "A base project to support the development of the Warning Apps"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.1

  sentry: ^7.18.0

  fogos_api: 0.0.4+1
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  responsive_framework: ^1.4.0
  get_it: ^7.7.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  flutter_svg: ^2.0.10+1
  dart_mappable: ^4.2.2
  wolt_modal_sheet: ^0.8.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.1.2
  json_serializable: ^6.7.1
  dart_mappable_builder: ^4.2.3

flutter:

  uses-material-design: true