name: fogosmobile
description: Fogos.pt new iOS and Android app

version: 5.0.1+500010

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_mappable: ^4.2.2
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  flutter_test:
    sdk: flutter
  melos: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/partners/