name: fogospt
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  go_router: ^14.2.1

  logger: ^2.0.2+1
  equatable: ^2.0.2
  freezed: ^2.4.7
  sentry: ^7.18.0

  fogos_api: 0.0.2
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  responsive_framework: ^1.4.0
  get_it: ^7.7.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.1.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true