name: fogos_api
description: "A new Flutter package project."
version: 0.0.2
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  warnings_api: 0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.1.2
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter: