name: warnings_api
description: "A future implementation of generic Warnings API"
version: 0.0.2
publish_to: none

environment:
  sdk: ^3.3.0


dependencies: 
  sentry: ^7.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1